name: speedtest
on:
  workflow_dispatch:

jobs:
  long_running_job:
    runs-on: ubuntu-latest
    steps:
          
      - name: 检出代码
        uses: actions/checkout@v5
        
      - name: 运行
        run: |
            sudo apt update && sudo apt install speedtest-cli -y
            for i in {1..3}; do speedtest --secure --share; done